# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: BlendLuxCore Blender Bundles

on:
  pull_request:
  push:
    branches:
      - for_blender_4.2_wheels
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_bundles:
    name: Build bundles
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Prepare Blender install
        uses: gerlero/apt-install@v1
        with:
          packages: libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libgl1

      - name: Prepare Python
        run: touch requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Fetch build dependencies
        run: |
          pip install --upgrade pip
          pip install tomlkit

      - uses: moguri/setup-blender@v1
        with:
          blender-version: '4.2.4'

      - run: blender --version

      - name: Get BlendLuxCore version (according to blender_manifest.toml)
        shell: python
        run: |
          import tomllib
          import os
          from pathlib import Path

          root = Path("${{ github.workspace }}")
          manifest_path = root / "blender_manifest.toml"
          with open(manifest_path, "rb") as fp:
              manifest = tomllib.load(fp)
          version = manifest["version"]

          # Version is stored in environment variable VERSION
          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "a") as myfile:
              myfile.write(f"VERSION={version}")

      - name: Package bundle
        shell: bash
        run: |
          echo "Packaging ${VERSION}"
          blender --command extension build \
            --source-dir "${{ github.workspace }}" \
            --output-dir "${{ github.workspace }}"
          unzip -q "BlendLuxCore-${VERSION}.zip" -d "${{ github.workspace }}/build"


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "BlendLuxCore-${{ env.VERSION }}"
          path: "${{ github.workspace }}/build/*"

